apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-inmy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-inmy@sha256:3e31db88b6dd85a1e31d8490eafd4ccc74ff81bfb53c6a42bc2b1ca4d72c23b6
        name: my-nodejs
        resources: {}
status: {}
